# Generated by Django 4.2.7 on 2023-11-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
