# Generated by Django 4.2.7 on 2023-11-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0004_alter_chat_user_1_alter_chat_user_2_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messages',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
