# Generated by Django 4.2.7 on 2023-11-18 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0005_alter_message_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
